### ISSUE TITLE
[de] german web page without panel 3

### ISSUE THREAD

**Issue by phellmes** [Deevad/peppercarrot_ep05_translation#4]
Hi David,

I've just noticed that the web page with the German translation of episode 5 misses panel 3. At first I thought that the image didn't load but I inspected the html source and it's just not there at all.
Would be nice if you could have a look into this.

Helmar

**Comment by Deevad** [comment]
Hi Helmar, 

Thank you for noticing it, it was hard to notice! 
 I confirm and fixed it. (  I think I had a FTP error. )
